// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../encoding/json/models.js";

/**
 * Caps says what this machine can do with files, so the menus can say
 * "Move to Trash" or "Delete", "Reveal in Finder" or nothing.
 */
export interface Caps {
    /**
     * Remove moves to the Trash rather than deleting
     */
    "trash": boolean;

    /**
     * the file browser's name, "" if there is none to open
     */
    "reveal": string;

    /**
     * runtime.GOOS: the page leaves room for macOS's inline traffic lights
     */
    "os": string;
}

/**
 * ChatEvent is one thing the page shows: a line of text, a tool Claude
 * used, the end of a turn.
 */
export interface ChatEvent {
    /**
     * init | text | tool | result | error | done | log
     */
    "kind": string;
    "text"?: string;
    "name"?: string;
    "input"?: string;
    "session"?: string;
    "cost"?: number;
    "model"?: string;

    /**
     * "none" when a plan pays, else the API key's origin
     */
    "keySource"?: string;
}

/**
 * ChatInfo says whether Claude Code is on this machine, and whose it is:
 * the login (a claude.ai plan, or an API key) decides what a turn costs
 * the user, so the page can say so.
 */
export interface ChatInfo {
    "found": boolean;
    "path": string;
    "busy": boolean;
    "loggedIn": boolean;

    /**
     * "claude.ai" for a plan, else an API key or nothing
     */
    "authMethod": string;
    "email": string;

    /**
     * "max", "pro", … when the login is claude.ai
     */
    "plan": string;
    "org": string;
}

/**
 * FileInfo is what the browser knows of a file before anyone opens it.
 */
export interface FileInfo {
    /**
     * "2D", "3D", "palette", "scene" or "3D scene"
     */
    "kind": string;

    /**
     * the palette files it draws from, as it names them
     */
    "refs": string[] | null;
}

/**
 * GitChange is one line of `git status`: what happened to a file, and
 * its path from the project's root.
 */
export interface GitChange {
    /**
     * M, A, D, R or ? (untracked)
     */
    "status": string;
    "path": string;
}

/**
 * GitProgress is a line of a clone as it runs.
 */
export interface GitProgress {
    "message": string;

    /**
     * 0..1, -1 when git did not say
     */
    "done": number;
}

/**
 * PopupItem is one row of a native menu the page describes. The page keeps
 * what each row does; a click comes back as the row's id on "popup".
 */
export interface PopupItem {
    "id": string;
    "label": string;
    "separator": boolean;
    "disabled": boolean;
    "checked": boolean;
    "keys": string;
    "items": PopupItem[] | null;
}

export interface ServeInfo {
    "on": boolean;
    "url": string;
    "root": string;

    /**
     * a PNG data URL of the URL, for the screen
     */
    "qr": string;
}

/**
 * Text is a file's content and whether there was one.
 */
export interface Text {
    "text": string;
    "found": boolean;
}

/**
 * ToolCall is what the page receives: a call to answer with ToolReply.
 */
export interface ToolCall {
    "id": string;
    "name": string;
    "args": json$0.RawMessage;
}

export interface UpdateInfo {
    "current": string;
    "latest": string;
    "available": boolean;

    /**
     * the release page, and the asset for this machine ("" when the release has none)
     */
    "url": string;
    "assetUrl": string;
    "asset": string;
    "size": number;
    "notes": string;
}

/**
 * UpdateProgress: what the frontend shows while an update lands.
 */
export interface UpdateProgress {
    /**
     * download | unpack | install | done | error
     */
    "phase": string;
    "done": number;
    "total": number;
    "message": string;
}
