// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Caps says what this machine can do with files, so the menus can say
 * "Move to Trash" or "Delete", "Reveal in Finder" or nothing.
 */
export interface Caps {
    /**
     * Remove moves to the Trash rather than deleting
     */
    "trash": boolean;

    /**
     * the file browser's name, "" if there is none to open
     */
    "reveal": string;
}

export interface ServeInfo {
    "on": boolean;
    "url": string;
    "root": string;

    /**
     * a PNG data URL of the URL, for the screen
     */
    "qr": string;
}
