// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ServeInfo {
    "on": boolean;
    "url": string;
    "root": string;

    /**
     * a PNG data URL of the URL, for the screen
     */
    "qr": string;
}
