// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DefaultRoot is the terminal's directory when the studio was launched
 * from one; launched from the Finder (cwd / or the home folder) it is "",
 * and the welcome screen takes over.
 */
export function DefaultRoot(): $CancellablePromise<string> {
    return $Call.ByID(1778093797);
}

export function DrainOpenQueue(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3935871685);
}

export function Exists(root: string, rel: string): $CancellablePromise<boolean> {
    return $Call.ByID(3095028904, root, rel);
}

export function ForgetRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1309726106, root);
}

export function Home(): $CancellablePromise<string> {
    return $Call.ByID(447982831);
}

export function IsDir(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2956617335, path);
}

export function ListFiles(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2880338351, root);
}

/**
 * PickFolder shows the platform's folder dialog. "" means cancelled.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2105207105);
}

export function PushRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(150194679, root);
}

export function ReadFile(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(1365949130, root, rel);
}

export function Recents(): $CancellablePromise<string[] | null> {
    return $Call.ByID(865853008);
}

export function Serve(root: string): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1611635379, root);
}

export function ServeStatus(): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1513706789);
}

export function ServeStop(): $CancellablePromise<void> {
    return $Call.ByID(935075611);
}

/**
 * WriteFile writes text under root, creating folders on the way ("enemies/bat.fart").
 */
export function WriteFile(root: string, rel: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1511688169, root, rel, text);
}
