// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Caps: what this machine can do with files (see files.go).
 */
export function Caps(): $CancellablePromise<$models.Caps> {
    return $Call.ByID(2879812873);
}

export function ChatAsk(root: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(1709244691, root, prompt);
}

export function ChatReset(root: string): $CancellablePromise<void> {
    return $Call.ByID(4107291937, root);
}

export function ChatStatus(): $CancellablePromise<$models.ChatInfo> {
    return $Call.ByID(1432761136);
}

export function ChatStop(): $CancellablePromise<void> {
    return $Call.ByID(861300774);
}

export function Checkout(): $CancellablePromise<string> {
    return $Call.ByID(100392916);
}

/**
 * DefaultRoot is the terminal's directory when the studio was launched
 * from one; launched from the Finder (cwd / or the home folder) it is "",
 * and the welcome screen takes over.
 */
export function DefaultRoot(): $CancellablePromise<string> {
    return $Call.ByID(1778093797);
}

export function DrainOpenQueue(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3935871685);
}

/**
 * Duplicate copies a file beside itself and returns the copy's relative path.
 */
export function Duplicate(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(230797401, root, rel);
}

export function Exists(root: string, rel: string): $CancellablePromise<boolean> {
    return $Call.ByID(3095028904, root, rel);
}

export function FindNamed(base: string, name: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3276632228, base, name);
}

export function ForgetRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1309726106, root);
}

export function GitRoot(dir: string): $CancellablePromise<string> {
    return $Call.ByID(151827472, dir);
}

export function Home(): $CancellablePromise<string> {
    return $Call.ByID(447982831);
}

export function IsDir(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2956617335, path);
}

export function ListFiles(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2880338351, root);
}

/**
 * Log prints a line from the page into the shell's log (a debugging aid).
 */
export function Log(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2147002042, msg);
}

/**
 * PickFolder shows the platform's folder dialog. "" means cancelled.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2105207105);
}

export function PushRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(150194679, root);
}

/**
 * ReadAt reads rel under an absolute base folder (the home folder, a repo root).
 */
export function ReadAt(base: string, rel: string): $CancellablePromise<$models.Text> {
    return $Call.ByID(2325224713, base, rel);
}

export function ReadFile(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(1365949130, root, rel);
}

export function Recents(): $CancellablePromise<string[] | null> {
    return $Call.ByID(865853008);
}

/**
 * Remove takes a file out of the project: to the Trash where there is
 * one, else deleted. Returns "trash" or "deleted".
 */
export function Remove(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(3488627824, root, rel);
}

/**
 * Rename moves a file within the project ("hero.fart" to "enemies/boss.fart").
 */
export function Rename(root: string, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(4872810, root, $from, to);
}

/**
 * Reveal shows a file or folder in the system's file browser; "" is the project itself.
 */
export function Reveal(root: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(2085297517, root, rel);
}

export function Serve(root: string): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1611635379, root);
}

export function ServeStatus(): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1513706789);
}

export function ServeStop(): $CancellablePromise<void> {
    return $Call.ByID(935075611);
}

/**
 * Stat says whether rel exists under root and when it was last written (unix ms).
 */
export function Stat(root: string, rel: string): $CancellablePromise<$models.Text> {
    return $Call.ByID(3774745978, root, rel);
}

/**
 * ToolReply is the page answering a tool call the MCP server relayed to it.
 */
export function ToolReply(id: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(4119343630, id, result);
}

/**
 * WriteAt writes rel under an absolute base folder, making folders on the way.
 */
export function WriteAt(base: string, rel: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1466586722, base, rel, text);
}

/**
 * WriteFile writes text under root, creating folders on the way ("enemies/bat.fart").
 */
export function WriteFile(root: string, rel: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1511688169, root, rel, text);
}
