// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Branch is the branch the project's repository has checked out, "" when
 * the folder is not in a repository (or git is not installed). A detached
 * HEAD reads as its short hash.
 */
export function Branch(dir: string): $CancellablePromise<string> {
    return $Call.ByID(2558730392, dir);
}

/**
 * Branches lists the repository's local branches, the current one included.
 */
export function Branches(dir: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3363503068, dir);
}

/**
 * Caps: what this machine can do with files (see files.go).
 */
export function Caps(): $CancellablePromise<$models.Caps> {
    return $Call.ByID(2879812873);
}

export function ChatAsk(root: string, prompt: string): $CancellablePromise<void> {
    return $Call.ByID(1709244691, root, prompt);
}

export function ChatReset(root: string): $CancellablePromise<void> {
    return $Call.ByID(4107291937, root);
}

export function ChatStatus(): $CancellablePromise<$models.ChatInfo> {
    return $Call.ByID(1432761136);
}

export function ChatStop(): $CancellablePromise<void> {
    return $Call.ByID(861300774);
}

export function Checkout(): $CancellablePromise<string> {
    return $Call.ByID(100392916);
}

/**
 * CloseWindow is the launcher's close light.
 */
export function CloseWindow(): $CancellablePromise<void> {
    return $Call.ByID(1832720096);
}

/**
 * DefaultRoot is the terminal's directory when the studio was launched
 * from one; launched from the Finder (cwd / or the home folder) it is "",
 * and the welcome screen takes over.
 */
export function DefaultRoot(): $CancellablePromise<string> {
    return $Call.ByID(1778093797);
}

export function DrainOpenQueue(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3935871685);
}

/**
 * Duplicate copies a file beside itself and returns the copy's relative path.
 */
export function Duplicate(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(230797401, root, rel);
}

export function Exists(root: string, rel: string): $CancellablePromise<boolean> {
    return $Call.ByID(3095028904, root, rel);
}

export function FindNamed(base: string, name: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(3276632228, base, name);
}

export function ForgetRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1309726106, root);
}

/**
 * Fullscreen says whether the window is full screen right now.
 */
export function Fullscreen(): $CancellablePromise<boolean> {
    return $Call.ByID(2439434473);
}

/**
 * GitClone clones url into <parent>/<name of the repository> and answers
 * with the new folder. Git's progress is relayed on "git" as it comes.
 */
export function GitClone(url: string, parent: string): $CancellablePromise<string> {
    return $Call.ByID(2042867317, url, parent);
}

/**
 * GitCommit stages everything under the project and commits it.
 */
export function GitCommit(dir: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3204675157, dir, message);
}

/**
 * GitInit makes the project a repository, if it is not one already.
 */
export function GitInit(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2872777578, dir);
}

export function GitRoot(dir: string): $CancellablePromise<string> {
    return $Call.ByID(151827472, dir);
}

/**
 * GitStatus lists what is uncommitted under the project.
 */
export function GitStatus(dir: string): $CancellablePromise<$models.GitChange[] | null> {
    return $Call.ByID(46096378, dir);
}

export function Home(): $CancellablePromise<string> {
    return $Call.ByID(447982831);
}

/**
 * IgnoreSidecars adds *.fart.glb to the project's .gitignore.
 */
export function IgnoreSidecars(root: string): $CancellablePromise<void> {
    return $Call.ByID(1941078042, root);
}

export function IsDir(path: string): $CancellablePromise<boolean> {
    return $Call.ByID(2956617335, path);
}

/**
 * Kinds is every file of the project and what it is ("2D", "3D",
 * "palette", "scene", "3D scene"), without parsing any of them.
 */
export function Kinds(root: string): $CancellablePromise<{ [_ in string]?: $models.FileInfo } | null> {
    return $Call.ByID(1108223755, root);
}

export function ListFiles(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2880338351, root);
}

/**
 * Log prints a line from the page into the shell's log (a debugging aid).
 */
export function Log(msg: string): $CancellablePromise<void> {
    return $Call.ByID(2147002042, msg);
}

/**
 * NewBranch makes a branch from where the project is and switches to it.
 */
export function NewBranch(dir: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(3014102262, dir, name);
}

/**
 * NewProject makes <parent>/<name> with an assets folder and a .gitignore
 * for the checkpoints, and returns the new root. It refuses to touch a
 * folder that already exists.
 */
export function NewProject(parent: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(1830481623, parent, name);
}

/**
 * PickFile shows the platform's open dialog inside the project and answers
 * with the file's path from the project's root. "" means cancelled; a file
 * outside the project is refused, since a project only names its own files.
 */
export function PickFile(root: string, dir: string, title: string, button: string, exts: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(1032951431, root, dir, title, button, exts);
}

/**
 * PickFolder shows the platform's folder dialog. "" means cancelled.
 */
export function PickFolder(): $CancellablePromise<string> {
    return $Call.ByID(2105207105);
}

/**
 * PickFolderAt is the folder dialog with its own words, for a new project's
 * home and a clone's destination. "" means cancelled.
 */
export function PickFolderAt(title: string, button: string): $CancellablePromise<string> {
    return $Call.ByID(1349797788, title, button);
}

/**
 * PickImport shows the platform's open dialog for a model, anywhere on
 * disk, and answers with its path. "" means cancelled.
 */
export function PickImport(): $CancellablePromise<string> {
    return $Call.ByID(4106690584);
}

/**
 * PickParentFolder shows the folder dialog for a new project's home. "" means cancelled.
 */
export function PickParentFolder(): $CancellablePromise<string> {
    return $Call.ByID(1601152289);
}

/**
 * PopupMenu shows the platform's context menu at a point of the page.
 */
export function PopupMenu(items: $models.PopupItem[] | null, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(4289174141, items, x, y);
}

export function PushRecent(root: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(150194679, root);
}

/**
 * ReadAt reads rel under an absolute base folder (the home folder, a repo root).
 */
export function ReadAt(base: string, rel: string): $CancellablePromise<$models.Text> {
    return $Call.ByID(2325224713, base, rel);
}

export function ReadFile(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(1365949130, root, rel);
}

/**
 * ReadImage is an image file of the project as a data URL, for a
 * reference image behind a model. Only pictures: anything else is refused.
 */
export function ReadImage(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(1453263833, root, rel);
}

/**
 * ReadImport is a model's bytes (uri ""), or those of a file a .gltf
 * names beside itself, as base64.
 */
export function ReadImport(path: string, uri: string): $CancellablePromise<string> {
    return $Call.ByID(2934376241, path, uri);
}

/**
 * ReadSidecar is a document's sidecar as base64, "" when it has none.
 */
export function ReadSidecar(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(2227100975, root, rel);
}

export function Recents(): $CancellablePromise<string[] | null> {
    return $Call.ByID(865853008);
}

/**
 * Remove takes a file out of the project: to the Trash where there is
 * one, else deleted. Returns "trash" or "deleted".
 */
export function Remove(root: string, rel: string): $CancellablePromise<string> {
    return $Call.ByID(3488627824, root, rel);
}

/**
 * Rename moves a file within the project ("hero.fart" to "enemies/boss.fart").
 */
export function Rename(root: string, $from: string, to: string): $CancellablePromise<void> {
    return $Call.ByID(4872810, root, $from, to);
}

/**
 * Reveal shows a file or folder in the system's file browser; "" is the project itself.
 */
export function Reveal(root: string, rel: string): $CancellablePromise<void> {
    return $Call.ByID(2085297517, root, rel);
}

export function Serve(root: string): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1611635379, root);
}

export function ServeStatus(): $CancellablePromise<$models.ServeInfo> {
    return $Call.ByID(1513706789);
}

export function ServeStop(): $CancellablePromise<void> {
    return $Call.ByID(935075611);
}

/**
 * SidecarIgnore: "none", "ignored" or "offer" (see sidecarIgnore).
 */
export function SidecarIgnore(root: string): $CancellablePromise<string> {
    return $Call.ByID(610483513, root);
}

/**
 * Stat says whether rel exists under root and when it was last written (unix ms).
 */
export function Stat(root: string, rel: string): $CancellablePromise<$models.Text> {
    return $Call.ByID(3774745978, root, rel);
}

/**
 * SwitchBranch checks a branch out. Git's own words come back when it
 * refuses (uncommitted changes in the way, most often).
 */
export function SwitchBranch(dir: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2027647100, dir, name);
}

/**
 * ToolReply is the page answering a tool call the MCP server relayed to it.
 */
export function ToolReply(id: string, result: string): $CancellablePromise<void> {
    return $Call.ByID(4119343630, id, result);
}

/**
 * UpdateApply downloads the asset and installs it in place of this app.
 * On macOS the .app bundle is replaced; on Linux the binary; on Windows
 * the binary is swapped by a helper after the app quits. Relaunch with
 * UpdateRelaunch when it reports done.
 */
export function UpdateApply(assetURL: string): $CancellablePromise<void> {
    return $Call.ByID(401870655, assetURL);
}

/**
 * UpdateCheck asks GitHub. Available is true when a newer studio release exists;
 * AssetURL is empty when it has no build for this machine yet (the workflow may still be running).
 */
export function UpdateCheck(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(779252731);
}

/**
 * UpdateRelaunch starts the installed build and quits this one.
 */
export function UpdateRelaunch(): $CancellablePromise<void> {
    return $Call.ByID(2213810503);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2791456436);
}

/**
 * WindowLauncher makes the window the launcher: small, fixed, centred.
 * The size it had is kept for WindowWork.
 */
export function WindowLauncher(): $CancellablePromise<void> {
    return $Call.ByID(2755277972);
}

/**
 * WindowWork grows the window back for a project.
 */
export function WindowWork(): $CancellablePromise<void> {
    return $Call.ByID(791676705);
}

/**
 * WriteAt writes rel under an absolute base folder, making folders on the way.
 */
export function WriteAt(base: string, rel: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1466586722, base, rel, text);
}

/**
 * WriteFile writes text under root, creating folders on the way ("enemies/bat.fart").
 */
export function WriteFile(root: string, rel: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(1511688169, root, rel, text);
}

/**
 * WriteSidecar writes a document's sidecar (base64 of a binary glTF).
 */
export function WriteSidecar(root: string, rel: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3285454450, root, rel, data);
}
