// Writes src/ui/icons.ts: the Lucide icons the studio draws, by name, as
// SVG bodies. Add a name here and run `node scripts/icons.mjs`.
import { icons } from "lucide";
import fs from "node:fs";

const NAMES = `folder folder-open folder-git-2 git-branch box layers search plus minus chevron-right chevron-down
chevron-left chevron-up chevrons-up-down panel-left panel-right mouse-pointer-2 square circle slash pentagon
grid-3x3 shield scan message-square contrast ellipsis play rotate-ccw image film person-standing map palette
package brick-wall ghost shirt layout-template file circle-dot download x check book-open settings move-3d
bone clock git-commit-horizontal hammer triangle-alert circle-check sun moon eye eye-off lock lock-open arrow-up
send undo-2 redo-2 trash-2 pause skip-back folder-plus file-plus refresh-cw external-link arrow-up-down
sliders-horizontal history pen-tool crosshair anchor circle-help copy pencil info wifi group magnet
list-tree spline blend square-dashed git-compare arrow-down panel-bottom monitor target link unlink flip-horizontal-2
maximize zoom-in corner-down-right circle-stop sparkles route paintbrush cylinder`.split(/\s+/);

const pascal = (n) => n.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const out = {};
for (const n of NAMES) {
	const node = icons[pascal(n)];
	if (!node) {
		console.warn(`no lucide icon named ${n}`);
		continue;
	}
	out[n] = node.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(" ")}/>`).join("");
}
const body = Object.entries(out).map(([k, v]) => `\t${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n");
fs.writeFileSync(new URL("../src/ui/icons.ts", import.meta.url), `// Generated by scripts/icons.mjs from Lucide (ISC). Do not edit by hand.\n\nexport const ICONS = {\n${body}\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n`);
console.log(`${Object.keys(out).length} icons`);
